/**
 * Which command module owns which command.
 *
 * Kept out of index.js so tests can import it without running `program.parse()`.
 */
export const ALL = [
  'setup', 'variables', 'daemon', 'tokens', 'gradient', 'create', 'url-tools',
  'config', 'canvas-ops', 'render', 'export-eval', 'analyze', 'a11y',
  'node-ops', 'slots', 'figjam', 'variants', 'misc', 'extract', 'rules',
  'snapshot', 'spec', 'instantiate', 'init', 'motion', 'styles',
];

/**
 * Command (or alias) → the modules that must be loaded to run it.
 *
 * Usually one module. A few commands forward to a command in ANOTHER module via
 * `program.parseAsync`, and those modules have to be present too — `import`
 * hands DESIGN.md work to `tokens import-design-md`, so loading only `setup`
 * would make it fail with "unknown command".
 *
 * tests/lazy-command-map.test.js regenerates this from the real Commander tree
 * and fails if a command is missing or a forward is undeclared, so the map
 * cannot silently drift away from the code.
 */
export const COMMAND_MODULES = {
  import: ['setup', 'tokens'],
  init: ['setup'],
  setup: ['setup'],
  status: ['setup'],
  unpatch: ['setup'],
  connect: ['setup'],
  variables: ['variables'],
  var: ['variables'],
  'delete-batch': ['variables'],
  'bind-batch': ['variables'],
  'set-batch': ['variables'],
  'rename-batch': ['variables'],
  daemon: ['daemon'],
  collections: ['tokens'],
  col: ['tokens'],
  tokens: ['tokens'],
  gradient: ['gradient'],
  create: ['create'],
  'screenshot-url': ['url-tools'],
  screenshot: ['url-tools'],
  'analyze-url': ['url-tools'],
  'recreate-url': ['url-tools'],
  recreate: ['url-tools'],
  'remove-bg': ['url-tools'],
  removebg: ['url-tools'],
  config: ['config'],
  canvas: ['canvas-ops'],
  bind: ['canvas-ops'],
  sizing: ['canvas-ops'],
  padding: ['canvas-ops'],
  pad: ['canvas-ops'],
  gap: ['canvas-ops'],
  align: ['canvas-ops'],
  select: ['canvas-ops'],
  delete: ['canvas-ops'],
  remove: ['canvas-ops'],
  duplicate: ['canvas-ops'],
  dup: ['canvas-ops'],
  set: ['canvas-ops'],
  pin: ['canvas-ops'],
  unwrap: ['canvas-ops'],
  use: ['canvas-ops'],
  theme: ['canvas-ops'],
  inspect: ['canvas-ops'],
  unstack: ['canvas-ops'],
  arrange: ['canvas-ops'],
  get: ['canvas-ops'],
  find: ['canvas-ops'],
  render: ['render'],
  'render-batch': ['render'],
  undo: ['render'],
  diagnose: ['render'],
  export: ['export-eval'],
  verify: ['export-eval'],
  eval: ['export-eval'],
  run: ['export-eval'],
  raw: ['export-eval'],
  lint: ['analyze'],
  analyze: ['analyze'],
  a11y: ['a11y'],
  node: ['node-ops'],
  slot: ['slots'],
  styles: ['styles'],
  'export-jsx': ['figjam'],
  'export-storybook': ['figjam'],
  figjam: ['figjam'],
  fj: ['figjam'],
  files: ['figjam'],
  sizes: ['variants'],
  variants: ['variants'],
  combos: ['variants'],
  shadcn: ['variants'],
  blocks: ['misc'],
  dev: ['misc'],
  section: ['misc'],
  grid: ['misc'],
  component: ['misc'],
  annotate: ['misc'],
  plugins: ['misc'],
  voice: ['misc'],
  chat: ['misc'],
  api: ['misc'],
  extract: ['extract'],
  rules: ['rules'],
  snapshot: ['snapshot'],
  check: ['snapshot'],
  spec: ['spec'],
  instantiate: ['instantiate'],
  'init-agent': ['init'],
  motion: ['motion'],
};
