#!/usr/bin/env node

/**
 * Figma CLI Daemon
 *
 * Supports two modes:
 * - Yolo Mode (CDP): Direct connection via Chrome DevTools Protocol (fast, requires patching)
 * - Safe Mode (Plugin): Connection via Figma plugin WebSocket (secure, no patching)
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { FigmaClient } from './figma-client.js';

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const MODE = process.env.DAEMON_MODE || 'auto'; // 'auto', 'cdp', 'plugin'
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 10 * 60 * 1000; // Default: 10 minutes

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.figma-ds-cli', '.daemon-token');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all requests.');
  console.error('[daemon] Token expected at: ' + TOKEN_FILE);
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes)
  const token = req.headers['x-daemon-token'];
  if (!SESSION_TOKEN) {
    return 'No session token configured';
  }
  if (token !== SESSION_TOKEN) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer();

// CDP Client (Yolo Mode)
let cdpClient = null;
let isCdpConnecting = false;

// Plugin Client (Safe Mode)
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

// ============ CDP MODE (YOLO) ============

async function isCdpHealthy() {
  if (!cdpClient || !cdpClient.ws) return false;
  if (cdpClient.ws.readyState !== 1) return false;

  try {
    const result = await Promise.race([
      cdpClient.eval('typeof figma !== "undefined"'),
      new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 2000))
    ]);
    return result === true;
  } catch {
    return false;
  }
}

async function getCdpClient() {
  if (cdpClient) {
    const healthy = await isCdpHealthy();
    if (healthy) return cdpClient;

    console.log('[daemon] CDP connection stale, reconnecting...');
    try { cdpClient.close(); } catch { }
    cdpClient = null;
  }

  if (isCdpConnecting) {
    while (isCdpConnecting) {
      await new Promise(r => setTimeout(r, 100));
    }
    return cdpClient;
  }

  isCdpConnecting = true;
  try {
    cdpClient = new FigmaClient();
    await cdpClient.connect();
    console.log('[daemon] Connected to Figma via CDP (Yolo Mode)');
  } finally {
    isCdpConnecting = false;
  }
  return cdpClient;
}

async function evalViaCdp(code) {
  const client = await getCdpClient();
  return client.eval(code);
}

// ============ PLUGIN MODE (SAFE) ============

function isPluginConnected() {
  return pluginWs && pluginWs.readyState === WebSocket.OPEN;
}

async function evalViaPlugin(code) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the Figma CLI Bridge plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout'));
    }, 30000);

    pluginPendingRequests.set(id, { resolve, reject, timeout });

    pluginWs.send(JSON.stringify({
      action: 'eval',
      id: id,
      code: code
    }));
  });
}

// ============ UNIFIED EVAL ============

async function executeEval(code) {
  // Auto mode: prefer plugin if connected, fallback to CDP
  if (MODE === 'auto') {
    if (isPluginConnected()) {
      return evalViaPlugin(code);
    }
    return evalViaCdp(code);
  }

  // Explicit mode
  if (MODE === 'plugin') {
    return evalViaPlugin(code);
  }

  return evalViaCdp(code);
}

function getMode() {
  if (MODE === 'plugin') return 'safe';
  if (MODE === 'cdp') return 'yolo';
  // Auto: return what's actually connected
  if (isPluginConnected()) return 'safe';
  if (cdpClient) return 'yolo';
  return 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // Reset idle timer on every request
  resetIdleTimer();

  // --- SECURITY: No CORS headers (blocks all cross-origin browser requests) ---
  // Intentionally omitted: Access-Control-Allow-Origin, Allow-Methods, Allow-Headers

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // --- SECURITY: Validate authentication on all routes ---
  const authError = validateRequest(req);
  if (authError) {
    console.log(`[daemon] Rejected request: ${authError} (${req.url})`);
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const mode = getMode();
    const pluginConnected = isPluginConnected();

    // Don't block health check if CDP is still connecting
    let cdpHealthy = false;
    if (isCdpConnecting) {
      // CDP connection in progress — report as connecting
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        status: 'connecting',
        mode: mode,
        plugin: pluginConnected,
        cdp: false,
        cdpConnecting: true,
        idleTimeoutMs: IDLE_TIMEOUT_MS
      }));
      return;
    }

    cdpHealthy = await isCdpHealthy();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: (pluginConnected || cdpHealthy) ? 'ok' : 'disconnected',
      mode: mode,
      plugin: pluginConnected,
      cdp: cdpHealthy,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Force reconnect (CDP only)
  if (req.url === '/reconnect') {
    try {
      if (cdpClient) {
        try { cdpClient.close(); } catch { }
        cdpClient = null;
      }
      await getCdpClient();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'reconnected', mode: 'yolo' }));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      const MAX_RETRIES = 2;
      let lastError;

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray } = JSON.parse(body);
          let result;

          const execWithTimeout = async (fn) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error('Execution timeout')), 30000)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code));
              break;
            case 'render':
              // Parse JSX to code, then execute via unified eval (works with both CDP and Plugin)
              const parser = new FigmaClient();
              const renderCode = parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode));
              break;
            case 'render-batch':
              const batchParser = new FigmaClient();
              result = [];
              for (const j of jsxArray) {
                const batchCode = batchParser.parseJSX(j);
                result.push(await execWithTimeout(() => executeEval(batchCode)));
              }
              break;
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result, mode: getMode() }));
          return;
        } catch (error) {
          lastError = error;
          console.log(`[daemon] Attempt ${attempt + 1} failed: ${error.message}`);

          // Force reconnect before retry (CDP only)
          if (attempt < MAX_RETRIES && !isPluginConnected()) {
            console.log('[daemon] Reconnecting before retry...');
            try { cdpClient.close(); } catch { }
            cdpClient = null;
            await new Promise(r => setTimeout(r, 500));
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: lastError.message }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections
const wss = new WebSocketServer({ server: httpServer, path: '/plugin' });

wss.on('connection', (ws) => {
  console.log('[daemon] Plugin connected (Safe Mode)');
  pluginWs = ws;
  resetIdleTimer(); // Plugin connection counts as activity

  ws.on('message', (data) => {
    resetIdleTimer(); // Plugin messages count as activity
    try {
      const msg = JSON.parse(data.toString());

      if (msg.type === 'hello') {
        console.log(`[daemon] Plugin version: ${msg.version}`);
      }

      if (msg.type === 'result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);

          if (msg.error) {
            pending.reject(new Error(msg.error));
          } else {
            pending.resolve(msg.result);
          }
        }
      }

      if (msg.type === 'pong') {
        // Health check response
      }
    } catch (e) {
      console.error('[daemon] Plugin message error:', e);
    }
  });

  ws.on('close', () => {
    console.log('[daemon] Plugin disconnected');
    pluginWs = null;

    // Reject all pending requests
    for (const [id, pending] of pluginPendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Plugin disconnected'));
    }
    pluginPendingRequests.clear();
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

httpServer.listen(PORT, '127.0.0.1', () => {
  console.log(`[daemon] Figma CLI daemon running on port ${PORT}`);
  console.log(`[daemon] Mode: ${MODE === 'auto' ? 'auto (plugin preferred, CDP fallback)' : MODE}`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (cdpClient) cdpClient.close();
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}

// In auto/cdp mode, pre-connect to Figma with retry
if (MODE !== 'plugin') {
  (async () => {
    const MAX_STARTUP_RETRIES = 5;
    const RETRY_DELAY_MS = 2000;
    for (let attempt = 1; attempt <= MAX_STARTUP_RETRIES; attempt++) {
      try {
        await getCdpClient();
        console.log(`[daemon] CDP connected on attempt ${attempt}`);
        return;
      } catch (err) {
        console.log(`[daemon] CDP connect attempt ${attempt}/${MAX_STARTUP_RETRIES} failed: ${err.message}`);
        if (attempt < MAX_STARTUP_RETRIES) {
          await new Promise(r => setTimeout(r, RETRY_DELAY_MS));
        }
      }
    }
    console.log('[daemon] CDP not available after retries, waiting for plugin connection or on-demand reconnect...');
  })();
}
