#!/usr/bin/env node

/**
 * Figma CLI Daemon
 *
 * Supports two modes:
 * - Yolo Mode (CDP): Direct connection via Chrome DevTools Protocol (fast, requires patching)
 * - Safe Mode (Plugin): Connection via Figma plugin WebSocket (secure, no patching)
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, statSync, writeFileSync, unlinkSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { homedir, tmpdir } from 'os';
import { fileURLToPath, pathToFileURL } from 'url';
import { wrapCodeIfNeeded } from './lib/eval-wrap.js';

// Hot-reload FigmaClient: copy to temp file and import (Node.js ES modules don't support cache busting)
const __dirname = dirname(fileURLToPath(import.meta.url));
const figmaClientPath = join(__dirname, 'figma-client.js');
let FigmaClient = null;
let lastModTime = 0;
let lastTempFile = null;

async function getFigmaClient() {
  try {
    const stat = statSync(figmaClientPath);
    const modTime = stat.mtimeMs;

    // Reload if file changed or never loaded
    if (!FigmaClient || modTime > lastModTime) {
      // Clean up old temp files in project directory (keeps node_modules accessible)
      try {
        const oldFiles = readdirSync(__dirname).filter(f => f.startsWith('.figma-client-') && f.endsWith('.mjs'));
        for (const f of oldFiles) {
          try { unlinkSync(join(__dirname, f)); } catch {}
        }
      } catch {}

      // Copy to temp file in same directory (so imports resolve correctly)
      const tempFile = join(__dirname, `.figma-client-${modTime}.mjs`);
      const content = readFileSync(figmaClientPath, 'utf8');
      writeFileSync(tempFile, content);
      lastTempFile = tempFile;

      // Import from temp file
      const tempUrl = pathToFileURL(tempFile).href;
      const module = await import(tempUrl);
      FigmaClient = module.FigmaClient;

      const wasReload = lastModTime > 0;
      lastModTime = modTime;
      if (wasReload) console.log('[daemon] Hot-reloaded figma-client.js');
    }
  } catch (e) {
    console.error('[daemon] Hot-reload error:', e.message);
    // Fallback: just import normally
    if (!FigmaClient) {
      const module = await import('./figma-client.js');
      FigmaClient = module.FigmaClient;
    }
  }
  return FigmaClient;
}

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const MODE = process.env.DAEMON_MODE || 'auto'; // 'auto', 'cdp', 'plugin'
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // Default: 60 minutes (long interactive design sessions have quiet stretches; the CLI also auto-restarts the daemon if it ever does shut down)

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.figma-ds-cli', '.daemon-token');
// This daemon owns the singleton PID file ONLY once it wins the port bind (see
// httpServer.listen below). The CLI no longer writes it, so the file always
// points at the daemon actually serving on the port — never a crashed loser.
const PID_FILE = join(homedir(), '.figma-cli-daemon.pid');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all requests.');
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes)
  const token = req.headers['x-daemon-token'];
  if (!SESSION_TOKEN) {
    return 'No session token configured';
  }
  if (token !== SESSION_TOKEN) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer()

// CDP Client (Yolo Mode)
let cdpClient = null;
let isCdpConnecting = false;
let lastHealthCheck = 0;
let lastHealthResult = false;
const HEALTH_CACHE_MS = 30000; // Cache health for 30 seconds (reduces overhead)

// Plugin Client (Safe Mode)
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

// ============ CDP MODE (YOLO) ============

async function isCdpHealthy(forceCheck = false) {
  // Quick WebSocket state check (no network call)
  if (!cdpClient || !cdpClient.ws) return false;
  if (cdpClient.ws.readyState !== 1) return false;

  // Use cached result if recent (avoids constant eval calls)
  const now = Date.now();
  if (!forceCheck && now - lastHealthCheck < HEALTH_CACHE_MS) {
    return lastHealthResult;
  }

  try {
    const result = await Promise.race([
      cdpClient.eval('1'), // Simple eval, just check connection works
      new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 2000))
    ]);
    lastHealthCheck = now;
    lastHealthResult = result === 1;
    return lastHealthResult;
  } catch {
    lastHealthCheck = now;
    lastHealthResult = false;
    return false;
  }
}

async function getCdpClient() {
  // Fast path: if we have a client with open WebSocket, use it
  if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
    return cdpClient;
  }

  // WebSocket closed, need to reconnect
  if (cdpClient) {
    console.log('[daemon] CDP WebSocket closed, reconnecting...');
    try { cdpClient.close(); } catch {}
    cdpClient = null;
    lastHealthResult = false;
  }

  // Wait if another connection attempt is in progress
  if (isCdpConnecting) {
    while (isCdpConnecting) {
      await new Promise(r => setTimeout(r, 100));
    }
    // The other attempt may have failed and left cdpClient null —
    // fall through and try connecting ourselves instead of returning null.
    if (cdpClient && cdpClient.ws && cdpClient.ws.readyState === 1) {
      return cdpClient;
    }
  }

  isCdpConnecting = true;
  try {
    const ClientClass = await getFigmaClient();
    cdpClient = new ClientClass();
    // FIGMA_FILE pins the daemon to a specific open file (substring match on the
    // tab title). Without it Figma's first design tab wins, which silently sends
    // commands to the wrong file when several are open.
    await cdpClient.connect(process.env.FIGMA_FILE || null);
    lastHealthCheck = Date.now();
    lastHealthResult = true;
    console.log('[daemon] Connected to Figma via CDP (Yolo Mode)');
  } finally {
    isCdpConnecting = false;
  }
  return cdpClient;
}

async function evalViaCdp(code) {
  const client = await getCdpClient();
  return client.eval(code);
}

// ============ PLUGIN MODE (SAFE) ============

function isPluginConnected() {
  return pluginWs && pluginWs.readyState === WebSocket.OPEN;
}

async function evalViaPlugin(code, retryCount = 0) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the Figma CLI Bridge plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout (25s)'));
    }, 25000); // 25s timeout to match plugin-side timeout

    pluginPendingRequests.set(id, { resolve, reject, timeout, code, retryCount });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval',
        id: id,
        code: code
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// Batch eval via plugin (execute multiple codes, return all results)
async function evalBatchViaPlugin(codes) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the Figma CLI Bridge plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin batch execution timeout (60s)'));
    }, 60000); // 60s for batches

    pluginPendingRequests.set(id, { resolve, reject, timeout, isBatch: true });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval-batch',
        id: id,
        codes: codes
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin batch send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============


async function executeEval(code) {
  // Auto mode: prefer plugin if connected, fallback to CDP
  if (MODE === 'auto') {
    if (isPluginConnected()) {
      // Plugin handles its own wrapping, send code as-is
      return evalViaPlugin(code);
    }
    // CDP needs wrapping for top-level return statements
    return evalViaCdp(wrapCodeIfNeeded(code));
  }

  // Explicit mode
  if (MODE === 'plugin') {
    // Plugin handles its own wrapping
    return evalViaPlugin(code);
  }

  // CDP mode
  return evalViaCdp(wrapCodeIfNeeded(code));
}

function getMode() {
  if (MODE === 'plugin') return 'safe';
  if (MODE === 'cdp') return 'yolo';
  // Auto: return what's actually connected
  if (isPluginConnected()) return 'safe';
  if (cdpClient) return 'yolo';
  return 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // Reset idle timer on every request
  resetIdleTimer();

  // SECURITY: No CORS headers (blocks all cross-origin browser requests)

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const mode = getMode();
    const pluginConnected = isPluginConnected();
    const cdpHealthy = await isCdpHealthy();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: (pluginConnected || cdpHealthy) ? 'ok' : 'disconnected',
      mode: mode,
      plugin: pluginConnected,
      cdp: cdpHealthy,
      // Which open file this daemon is bound to. The CLI compares it against
      // FIGMA_FILE and rebinds when they diverge — otherwise commands silently
      // hit whichever file happened to be first when the daemon started.
      file: (cdpClient && cdpClient.pageTitle) || null,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Force reconnect (CDP only)
  if (req.url === '/reconnect') {
    try {
      if (cdpClient) {
        try { cdpClient.close(); } catch {}
        cdpClient = null;
      }
      await getCdpClient();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'reconnected', mode: 'yolo' }));
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      const MAX_RETRIES = 2;
      let lastError;

      // Parse once, outside the retry loop — a malformed body never becomes
      // valid by retrying, and retries used to tear down a healthy CDP
      // connection for it.
      let payload;
      try {
        payload = JSON.parse(body);
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
        return;
      }

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray, gap, vertical, collection, autoStyle } = payload;
          let result;

          const execWithTimeout = async (fn, timeoutMs = 30000) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error(`Execution timeout (${timeoutMs/1000}s)`)), timeoutMs)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code));
              break;
            case 'render': {
              // Parse JSX to code, then execute via unified eval (works with both CDP and Plugin)
              const ClientClass = await getFigmaClient();
              const parser = new ClientClass();
              const renderCode = await parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode), 90000); // 90s for renders with icons
              break;
            }
            case 'render-batch': {
              // Single eval for ALL frames (10x faster than loop)
              const ClientClass = await getFigmaClient();
              const batchParser = new ClientClass();
              if (collection) batchParser.setCollection(collection);
              if (autoStyle === false) batchParser.setAutoTextStyle(false);
              const batchCode = await batchParser.parseJSXBatch(jsxArray, {
                gap: gap || 40,
                vertical: vertical || false
              });
              result = await execWithTimeout(() => executeEval(batchCode), 60000); // 60s for batches
              break;
            }
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result, mode: getMode() }));
          return;
        } catch (error) {
          lastError = error;
          console.log(`[daemon] Attempt ${attempt + 1} failed: ${error.message}`);

          // NEVER retry a mutating render: executeEval may have already created
          // the frame before the response errored (a transient CDP hiccup under
          // load, e.g. several heavy files open). Retrying re-runs the render
          // code and silently produces a DUPLICATE frame. Fail fast instead —
          // a clear error beats a phantom copy. (Reads/eval may still retry.)
          if (payload.action === 'render' || payload.action === 'render-batch') break;

          // For Safe Mode: wait briefly for potential reconnect
          if (attempt < MAX_RETRIES && MODE === 'plugin') {
            console.log('[daemon] Safe Mode: waiting for plugin reconnect...');
            // Wait up to 2s for plugin to reconnect
            for (let i = 0; i < 10; i++) {
              await new Promise(r => setTimeout(r, 200));
              if (isPluginConnected()) {
                console.log('[daemon] Plugin reconnected, retrying...');
                break;
              }
            }
          }

          // For Yolo Mode: only reconnect when the connection is actually
          // broken. If CDP is healthy, the error came from the executed code
          // itself — retrying would just re-run it (and a timed-out render
          // would create duplicate nodes).
          if (attempt < MAX_RETRIES && MODE !== 'plugin' && !isPluginConnected()) {
            if (await isCdpHealthy(true)) {
              console.log('[daemon] CDP healthy — error is not connection-related, not retrying');
              break;
            }
            console.log('[daemon] Reconnecting CDP before retry...');
            // Don't tear down a connection another request is currently building
            if (!isCdpConnecting) {
              try { if (cdpClient) cdpClient.close(); } catch {}
              cdpClient = null;
            }
            // Backoff: 300ms after first failure, 1s after second
            await new Promise(r => setTimeout(r, attempt === 0 ? 300 : 1000));
            try {
              await getCdpClient();
              if (!(await isCdpHealthy(true))) {
                console.log('[daemon] CDP still unhealthy after reconnect');
              }
            } catch (reconnectError) {
              console.log('[daemon] CDP reconnect failed: ' + reconnectError.message);
            }
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: (lastError && lastError.message) || 'Execution failed' }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections
const wss = new WebSocketServer({ server: httpServer, path: '/plugin' });

wss.on('connection', (ws) => {
  console.log('[daemon] Plugin connected (Safe Mode)');
  pluginWs = ws;
  resetIdleTimer(); // Plugin connection counts as activity

  ws.on('message', (data) => {
    resetIdleTimer(); // Plugin messages count as activity
    try {
      const msg = JSON.parse(data.toString());

      if (msg.type === 'hello') {
        console.log(`[daemon] Plugin version: ${msg.version}`);
      }

      if (msg.type === 'result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);

          if (msg.error) {
            pending.reject(new Error(msg.error));
          } else {
            pending.resolve(msg.result);
          }
        }
      }

      // Batch result from plugin
      if (msg.type === 'batch-result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);
          pending.resolve(msg.results);
        }
      }

      // Keepalive ping from plugin
      if (msg.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong' }));
      }

      if (msg.type === 'pong') {
        // Health check response
      }
    } catch (e) {
      console.error('[daemon] Plugin message error:', e);
    }
  });

  ws.on('close', () => {
    console.log('[daemon] Plugin disconnected');
    pluginWs = null;

    // Reject all pending requests
    for (const [id, pending] of pluginPendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Plugin disconnected'));
    }
    pluginPendingRequests.clear();
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

// Singleton guard: a second daemon spawned by a concurrent CLI invocation
// (startDaemon has a check-then-act race) will fail to bind the port. Exit it
// cleanly BEFORE it does any work, and do NOT let it touch the PID file — so the
// winner stays the one true daemon. Without this the loser used to crash on an
// unhandled 'error' while the CLI had already written ITS pid to the PID file,
// so isDaemonRunning() saw a dead pid and respawned endlessly (daemon churn →
// non-deterministic double execution).
httpServer.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    console.log(`[daemon] Port ${PORT} already owned by another daemon — exiting (singleton).`);
    process.exit(0);
  }
  console.error('[daemon] server error:', err);
  process.exit(1);
});

httpServer.listen(PORT, '127.0.0.1', () => {
  // We won the bind: claim the singleton PID file.
  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  console.log(`[daemon] Figma CLI daemon running on port ${PORT} (pid ${process.pid})`);
  console.log(`[daemon] Mode: ${MODE === 'auto' ? 'auto (plugin preferred, CDP fallback)' : MODE}`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (cdpClient) cdpClient.close();
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}

// In auto/cdp mode, pre-connect to Figma
if (MODE !== 'plugin') {
  getCdpClient().catch(err => {
    console.log('[daemon] CDP not available, waiting for plugin connection...');
  });
}
